Update backend-cd.yaml

diff --git a/.github/workflows/backend-cd.yaml b/.github/workflows/backend-cd.yaml
--- a/.github/workflows/backend-cd.yaml
+++ b/.github/workflows/backend-cd.yaml
@@ -115,3 +115,12 @@ jobs:
         run: |
           cd starter/backend/k8s
           kustomize build . | kubectl apply -f -
+
+      - name: Verify Deployment Status
+        run: |
+          if kubectl rollout status deployment/backend -n default --timeout=2m | grep -q 'deployment "backend" successfully rolled out'; then
+            echo "Deployment succeeded."
+          else
+            echo "Deployment failed."
+            exit 1
+          fi
