Update frontend-cd.yaml

diff --git a/.github/workflows/frontend-cd.yaml b/.github/workflows/frontend-cd.yaml
--- a/.github/workflows/frontend-cd.yaml
+++ b/.github/workflows/frontend-cd.yaml
@@ -131,3 +131,13 @@ jobs:
         run: |
           cd starter/frontend/k8s
           kustomize build . | kubectl apply -f -
+
+      - name: Verify Deployment Status
+        run: |
+          if kubectl rollout status deployment/frontend -n default --timeout=2m | grep -q 'deployment "frontend" successfully rolled out'; then
+            echo "Deployment succeeded."
+            exit 1
+          else
+            echo "Deployment failed."
+            exit 1
+          fi
